### PR TITLE
Fix badges in readme

### PR DESCRIPTION
**Pull request by perryprog**

### CODE REVIEW

**Comment by itsthejoker** [comment]
🤦‍♂️

**Comment by perryprog** [comment]
What?

**Comment by itsthejoker** [comment]
Just surprising that it's gone that long without fixing. I'll take a look here in a bit

**Comment by TheLonelyGhost** [comment]
Actually, there were some things wrong with this PR:

1. Links weren't tested. The Codacy link should have been changed to `https://www.codacy.com/app/TranscribersOfReddit/tor` to resolve correctly since the organization name is hardcoded on Codacy's side. That said, I just changed the org name over there to match the github org name since it made more sense to have `GrafeasGroup` in this case.
2. Every single link that changed should have also changed the shields.io links too. They're a third-party badge service that you punch in the link to the project and they'll display it nicer than the defaults.

Next time we should test the README changes by going to the fork's branch on github.com and looking at how they render it. I'll submit a PR to address these issues shortly.

**Comment by itsthejoker** [comment]
Whoops, that's on me. I just checked to make sure that they rendered, and for codacy (for example) it didn't resolve then and it doesn't resolve now -- I assumed that it was just something we needed to update on the back end anyway. My apologies.

**Pull request merged**
